importing R12B-4

diff --git a/lib/odbc/configure b/lib/odbc/configure
--- a/lib/odbc/configure
+++ b/lib/odbc/configure
@@ -4115,6 +4115,159 @@ have_odbc_lib=no
 
 
     case $host_os in
+        darwin*)
+                TARGET_FLAGS="-DUNIX"
+                echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
+if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_create ();
+int
+main ()
+{
+pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pthread_pthread_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pthread_pthread_create=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
+if test $ac_cv_lib_pthread_pthread_create = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBPTHREAD 1
+_ACEOF
+
+                            LIBS="$LIBS -lpthread"
+                            have_pthread_lib=yes
+fi
+
+	        if test ! -d "$with_odbc"; then
+		    ODBC_LIB= -L"/usr/lib"
+		    ODBC_INCLUDE="-I/usr/lib/include"
+		else
+		    ODBC_LIB=-L"$with_odbc/lib"
+		    ODBC_INCLUDE="-I$with_odbc/include"
+		fi
+
+               echo "$as_me:$LINENO: checking for SQLAllocHandle in -liodbc" >&5
+echo $ECHO_N "checking for SQLAllocHandle in -liodbc... $ECHO_C" >&6
+if test "${ac_cv_lib_iodbc_SQLAllocHandle+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liodbc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SQLAllocHandle ();
+int
+main ()
+{
+SQLAllocHandle ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iodbc_SQLAllocHandle=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_iodbc_SQLAllocHandle=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iodbc_SQLAllocHandle" >&5
+echo "${ECHO_T}$ac_cv_lib_iodbc_SQLAllocHandle" >&6
+if test $ac_cv_lib_iodbc_SQLAllocHandle = yes; then
+  ODBC_LIB="$ODBC_LIB -liodbc" odbc_lib_link_sucess=yes
+fi
+
+            ;;
         win32|cygwin)
 		TARGET_FLAGS="-DWIN32"
 
diff --git a/otp_build b/otp_build
--- a/otp_build
+++ b/otp_build
@@ -33,6 +33,9 @@ usage ()
     echo "release [-a] <target_dir> - creates full release to <target_dir>"
     echo "tests <dir> - Build testsuites to <dir>"
     echo ""
+    echo "remove_prebuilt_files - create a minimal source tree"
+    echo "save_bootstrap - recreate primary bootstrap"
+    echo ""
     echo "debuginfo_win32 <dir> - adds debug emulator and pdb files to <dir>"
     echo "installer_win32 <dir> - creates a windows installer from <dir>" 
     echo ""
@@ -680,6 +683,82 @@ do_installer_win32 ()
     (cd $installer_dir; $MAKE MAKE="$MAKE" TARGET=$TARGET TESTROOT=$1 release) || exit 1
 }
 
+do_copy_primary_bootstrap ()
+{
+    if [ "x$1" = "x" ]; then
+	echo "Missing bootstrap source top" 1>&2
+	exit 1
+    fi
+    if  [ ! -d $1 ]; then
+	echo "Invalid bootstrap source top" 1>&2
+	exit 1
+    fi
+    if [ "x$2" = "x" ]; then
+	echo "Missing bootstrap root" 1>&2
+	exit 1
+    fi
+    if  [ ! -d $2 ]; then
+	echo "Invalid bootstrap root" 1>&2
+	exit 1
+    fi
+
+    bootstrap=$2/bootstrap
+    bootstrap_src_top=$1
+    lib_src=$bootstrap_src_top/lib
+
+    # kernel
+    test -d $bootstrap/lib/kernel/ebin || mkdir -p  $bootstrap/lib/kernel/ebin
+    test -d $bootstrap/lib/kernel/include || mkdir -p  $bootstrap/lib/kernel/include
+    cp -f $lib_src/kernel/ebin/*.beam $bootstrap/lib/kernel/ebin
+    cp -f $lib_src/kernel/ebin/*.app* $bootstrap/lib/kernel/ebin
+    cp -f $lib_src/kernel/include/*.hrl $bootstrap/lib/kernel/include
+
+    # stdlib
+    test -d $bootstrap/lib/stdlib/ebin || mkdir -p  $bootstrap/lib/stdlib/ebin
+    test -d $bootstrap/lib/stdlib/include || mkdir -p  $bootstrap/lib/stdlib/include
+    cp -f $lib_src/stdlib/ebin/*.beam $bootstrap/lib/stdlib/ebin
+    cp -f $lib_src/stdlib/ebin/*.app* $bootstrap/lib/stdlib/ebin
+    cp -f $lib_src/stdlib/include/*.hrl $bootstrap/lib/stdlib/include
+
+    # compiler
+    test -d $bootstrap/lib/compiler/ebin || mkdir -p  $bootstrap/lib/compiler/ebin
+    cp -f $lib_src/compiler/ebin/*.beam $bootstrap/lib/compiler/ebin
+    cp -f $lib_src/compiler/ebin/*.app* $bootstrap/lib/compiler/ebin
+
+    # orber include
+    test -d $bootstrap/lib/orber/include || mkdir -p  $bootstrap/lib/orber/include
+    cp -f $lib_src/orber/include/* $bootstrap/lib/orber/include
+
+    # bootstrap bin
+    if [ $bootstrap_src_top != $ERL_TOP ]; then
+	test -d $bootstrap/bin || mkdir -p  $bootstrap/bin
+	cp -f $bootstrap_src_top/bin/* $bootstrap/bin
+    fi
+
+}
+
+do_save_bootstrap ()
+{
+    if [ ! -f $ERL_TOP/prebuilt.files ]; then
+	echo "This is not a pre-built source distribution" 1>&2
+	exit 1
+    fi
+    if  [ -d $ERL_TOP/bootstrap/lib ]; then
+	echo "Bootstrap already exist" 1>&2
+	exit 1
+    fi
+
+    do_copy_primary_bootstrap $ERL_TOP $ERL_TOP
+}
+
+do_remove_prebuilt_files ()
+{
+    do_save_bootstrap
+    for file in $ERL_TOP/`cat $ERL_TOP/prebuilt.files` ; do
+	rm -f $file
+    done
+}
+
 # main
 
 check_erltop
@@ -808,6 +887,12 @@ case "$1" in
 		    shift
 		fi;
 		do_tests "$2";;
+        remove_prebuilt_files)
+		do_remove_prebuilt_files;;
+        save_bootstrap)
+		do_save_bootstrap;;
+        copy_primary_bootstrap)
+		do_copy_primary_bootstrap $2 $3;;
 	installer_win32)
 		if [ $minus_a_flag = true ]; then 
 		    shift
