importing R10B-6

diff --git a/erts/configure b/erts/configure
--- a/erts/configure
+++ b/erts/configure
@@ -3692,7 +3692,7 @@ fi
 
 
 for ac_hdr in fcntl.h limits.h unistd.h syslog.h dlfcn.h ieeefp.h \
-                 poll.h sys/stropts.h \
+                 sys/stropts.h \
                  sys/ioctl.h sys/time.h sys/uio.h sys/sockio.h sys/socketio.h \
                  net/errno.h malloc.h mach-o/dyld.h arpa/nameser.h
 do
@@ -4867,7 +4867,7 @@ done
 
 
 for ac_func in ieee_handler fpsetmask finite isnan isinf res_gethostbyname dlopen \
-		poll pread pwrite writev memmove strerror strerror_r strncasecmp \
+		pread pwrite writev memmove strerror strerror_r strncasecmp \
 		gethrtime localtime_r gmtime_r mremap memcpy mallopt
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
@@ -6172,12 +6172,77 @@ EOF
 	;;
   *)
 	echo "$ac_t""not working" 1>&6
+
+			
+	echo $ac_n "checking if clock_gettime works""... $ac_c" 1>&6
+echo "configure:6179: checking if clock_gettime works" >&5
+	save_libs=$LIBS
+	LIBS="-lrt"
+	if test "$cross_compiling" = yes; then
+  erl_clock_gettime=false
+else
+  cat > conftest.$ac_ext <<EOF
+#line 6186 "configure"
+#include "confdefs.h"
+
+	#include <stdlib.h>
+	#include <unistd.h>
+	#include <string.h>
+	#include <stdio.h>
+	#include <time.h>
+	int main() {
+	    long long start, stop;
+	    int i;
+	    struct timespec tp;
+
+	    if (clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &tp) < 0)
+	      exit(1);
+	    start = ((long long)tp.tv_sec * 1000000000LL) + (long long)tp.tv_nsec;
+	    for (i = 0; i < 100; i++)
+	      clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &tp);
+	    stop = ((long long)tp.tv_sec * 1000000000LL) + (long long)tp.tv_nsec;
+	    if (start == 0)
+	      exit(4);
+	    if (start == stop)
+	      exit(5);
+	    exit(0); return 0;
+	  }
+	
+EOF
+if { (eval echo configure:6213: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  erl_clock_gettime=true
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  erl_clock_gettime=false
+fi
+rm -fr conftest*
+fi
+
+	LIBS=$save_libs
+	case $erl_clock_gettime in
+	  true)
+		cat >> confdefs.h <<\EOF
+#define HAVE_CLOCK_GETTIME 1
+EOF
+
+		echo "$ac_t""using clock_gettime" 1>&6
+		LIBRT=-lrt
+		;;
+	  *)
+		echo "$ac_t""not working" 1>&6
+		LIBRT=
+		;;
+	esac
+	
 	;;
 esac
 
 
 echo $ac_n "checking whether to redefine FD_SETSIZE""... $ac_c" 1>&6
-echo "configure:6181: checking whether to redefine FD_SETSIZE" >&5
+echo "configure:6246: checking whether to redefine FD_SETSIZE" >&5
 case $host_os in
   bsdi*)
 	cat >> confdefs.h <<\EOF
@@ -6249,7 +6314,7 @@ fi
 if test "x$HIPE_ENABLED" = "xyes" ; then
   if test "x$with_perfctr" = "x" ; then
       echo $ac_n "checking for vperfctr_info in -lperfctr""... $ac_c" 1>&6
-echo "configure:6253: checking for vperfctr_info in -lperfctr" >&5
+echo "configure:6318: checking for vperfctr_info in -lperfctr" >&5
 ac_lib_var=`echo perfctr'_'vperfctr_info | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -6257,7 +6322,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lperfctr  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 6261 "configure"
+#line 6326 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -6268,7 +6333,7 @@ int main() {
 vperfctr_info()
 ; return 0; }
 EOF
-if { (eval echo configure:6272: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6337: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -6330,6 +6395,64 @@ EOF
 
 fi
 
+#
+# Check for working poll().
+#
+echo $ac_n "checking for working poll()""... $ac_c" 1>&6
+echo "configure:6403: checking for working poll()" >&5
+if test "$cross_compiling" = yes; then
+  poll_works=false
+else
+  cat > conftest.$ac_ext <<EOF
+#line 6408 "configure"
+#include "confdefs.h"
+
+#include <poll.h>
+main()
+{
+#ifdef _POLL_EMUL_H_
+  exit(1); /* Implemented using select() -- fail */
+#else
+  struct pollfd fds[1];
+  int fd;
+  fd = open("/dev/null", 1);
+  fds[0].fd = fd;
+  fds[0].events = POLLIN;
+  fds[0].revents = 0;
+  if (poll(fds, 1, 0) < 0 || (fds[0].revents & POLLNVAL) != 0) {
+    exit(1);  /* Does not work for devices -- fail */
+  }
+  exit(0);
+#endif
+}
+
+EOF
+if { (eval echo configure:6431: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  poll_works=true
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  poll_works=false
+fi
+rm -fr conftest*
+fi
+
+case $poll_works in
+true)
+	echo "$ac_t""ok" 1>&6
+	;;
+*)
+	cat >> confdefs.h <<\EOF
+#define USE_SELECT 1
+EOF
+
+	echo "$ac_t""broken or based on select()" 1>&6
+	;;
+esac
+
+
 
 #--------------------------------------------------------------------
 # Dynamic Erlang Drivers
@@ -6363,6 +6486,7 @@ fi
 
 DED_LD=ld
 DED_LD_FLAG_RUNTIME_LIBRARY_PATH="-R"
+STATIC_CFLAGS=""
 
 case $host_os in
 	win32)
@@ -6387,6 +6511,7 @@ case $host_os in
 		DED_CFLAGS="$DED_CFLAGS -fno-common"
 		DED_LD="$CC"
 		DED_LD_FLAG_RUNTIME_LIBRARY_PATH=
+		STATIC_CFLAGS="-mdynamic-no-pic"
 	;;
 	osf*)
 		# NOTE! Whitespace after -rpath is important.
@@ -6401,16 +6526,16 @@ esac
 
 
 echo $ac_n "checking for compiler flags for loadable drivers""... $ac_c" 1>&6
-echo "configure:6405: checking for compiler flags for loadable drivers" >&5
+echo "configure:6530: checking for compiler flags for loadable drivers" >&5
 echo "$ac_t""$DED_CFLAGS" 1>&6
 echo $ac_n "checking for linker for loadable drivers""... $ac_c" 1>&6
-echo "configure:6408: checking for linker for loadable drivers" >&5
+echo "configure:6533: checking for linker for loadable drivers" >&5
 echo "$ac_t""$DED_LD" 1>&6
 echo $ac_n "checking for linker flags for loadable drivers""... $ac_c" 1>&6
-echo "configure:6411: checking for linker flags for loadable drivers" >&5
+echo "configure:6536: checking for linker flags for loadable drivers" >&5
 echo "$ac_t""$DED_LDFLAGS" 1>&6
 echo $ac_n "checking for 'runtime library path' linker flag""... $ac_c" 1>&6
-echo "configure:6414: checking for 'runtime library path' linker flag" >&5
+echo "configure:6539: checking for 'runtime library path' linker flag" >&5
 if test "x$DED_LD_FLAG_RUNTIME_LIBRARY_PATH" != "x"; then
 	echo "$ac_t""$DED_LD_FLAG_RUNTIME_LIBRARY_PATH" 1>&6
 else
@@ -6423,14 +6548,15 @@ fi
 
 
 
+
 echo $ac_n "checking for a compiler that handles jumptables""... $ac_c" 1>&6
-echo "configure:6428: checking for a compiler that handles jumptables" >&5
+echo "configure:6554: checking for a compiler that handles jumptables" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_emu_cc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   
 cat > conftest.$ac_ext <<EOF
-#line 6434 "configure"
+#line 6560 "configure"
 #include "confdefs.h"
 
 int main() {
@@ -6450,7 +6576,7 @@ lbl2:
 
 ; return 0; }
 EOF
-if { (eval echo configure:6454: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:6580: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_prog_emu_cc=$CC
 else
@@ -6487,7 +6613,7 @@ if test $ac_cv_prog_emu_cc != no; then
 	CFLAGS=""
 	CPPFLAGS=""
 	cat > conftest.$ac_ext <<EOF
-#line 6491 "configure"
+#line 6617 "configure"
 #include "confdefs.h"
 
 int main() {
@@ -6507,7 +6633,7 @@ int main() {
 	
 ; return 0; }
 EOF
-if { (eval echo configure:6511: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:6637: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_prog_emu_cc=$CC
 else
@@ -6571,7 +6697,7 @@ elif test "x$with_ssl" = "xyes" -o "x$with_ssl" = "x" ;then
     	# Extract the first word of "regtool", so it can be a program name with args.
 set dummy regtool; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:6575: checking for $ac_word" >&5
+echo "configure:6701: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_REGTOOL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6618,7 +6744,7 @@ fi
     SSH_APP=ssh
 
     echo $ac_n "checking for OpenSSL >= 0.9.7 in standard locations""... $ac_c" 1>&6
-echo "configure:6622: checking for OpenSSL >= 0.9.7 in standard locations" >&5 
+echo "configure:6748: checking for OpenSSL >= 0.9.7 in standard locations" >&5 
     for dir in $extra_dir /cygdrive/c/OpenSSL /usr/local /usr /usr/pkg \
 		/usr/local/openssl /usr/lib/openssl /usr/openssl \
 		/usr/local/ssl /usr/lib/ssl /usr/ssl
@@ -6654,7 +6780,7 @@ echo "configure:6622: checking for OpenSSL >= 0.9.7 in standard locations" >&5
 			old_CPPFLAGS=$CPPFLAGS
 			CPPFLAGS=$SSL_INCLUDE
 			cat > conftest.$ac_ext <<EOF
-#line 6658 "configure"
+#line 6784 "configure"
 #include "confdefs.h"
 
 #include <openssl/opensslv.h>
@@ -6734,11 +6860,11 @@ fi
 
 if test "x$SSL_APP" != "x" ; then
         echo $ac_n "checking for OpenSSL kerberos 5 support""... $ac_c" 1>&6
-echo "configure:6738: checking for OpenSSL kerberos 5 support" >&5
+echo "configure:6864: checking for OpenSSL kerberos 5 support" >&5
     old_CPPFLAGS=$CPPFLAGS
     CPPFLAGS=$SSL_INCLUDE
     cat > conftest.$ac_ext <<EOF
-#line 6742 "configure"
+#line 6868 "configure"
 #include "confdefs.h"
 
 #include <openssl/opensslconf.h>
@@ -6767,7 +6893,7 @@ rm -f conftest*
     SSL_KRB5_INCLUDE=
     if test "x$ssl_krb5_enabled" = "xyes" ; then
         echo $ac_n "checking for krb5.h in standard locations""... $ac_c" 1>&6
-echo "configure:6771: checking for krb5.h in standard locations" >&5
+echo "configure:6897: checking for krb5.h in standard locations" >&5
 	for dir in $extra_dir $SSL_ROOT/include $SSL_ROOT/include/openssl \
 		$SSL_ROOT/include/kerberos /cygdrive/c/kerberos/include \
 		/usr/local/kerberos/include /usr/kerberos/include
@@ -6798,7 +6924,7 @@ fi
 #--------------------------------------------------------------------
 
 echo $ac_n "checking for kstat_open in -lkstat""... $ac_c" 1>&6
-echo "configure:6802: checking for kstat_open in -lkstat" >&5
+echo "configure:6928: checking for kstat_open in -lkstat" >&5
 ac_lib_var=`echo kstat'_'kstat_open | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -6806,7 +6932,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lkstat  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 6810 "configure"
+#line 6936 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -6817,7 +6943,7 @@ int main() {
 kstat_open()
 ; return 0; }
 EOF
-if { (eval echo configure:6821: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6947: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -6856,7 +6982,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:6860: checking for $ac_word" >&5
+echo "configure:6986: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6887,7 +7013,7 @@ done
 
 if test -n "$JAVAC"; then
     echo $ac_n "checking for JDK version 1.2""... $ac_c" 1>&6
-echo "configure:6891: checking for JDK version 1.2" >&5
+echo "configure:7017: checking for JDK version 1.2" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_javac_ver_1_2'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6898,7 +7024,7 @@ class conftest { public static void main(String[] args) {
    java.util.Iterator iter;
    ; return; }}
 EOF
-if { (eval echo configure:6902: \"$java_link\") 1>&5; (eval $java_link) 2>&5; } && test -s conftest.class; then
+if { (eval echo configure:7028: \"$java_link\") 1>&5; (eval $java_link) 2>&5; } && test -s conftest.class; then
    rm -rf conftest*
    ac_cv_prog_javac_ver_1_2=yes
 else
@@ -6931,7 +7057,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:6935: checking for $ac_word" >&5
+echo "configure:7061: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CXX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7238,6 +7364,7 @@ s%@EMU_THR_DEFS@%$EMU_THR_DEFS%g
 s%@THR_LIBS@%$THR_LIBS%g
 s%@THR_DEFS@%$THR_DEFS%g
 s%@BITS64@%$BITS64%g
+s%@LIBRT@%$LIBRT%g
 s%@TSP_APP@%$TSP_APP%g
 s%@HIPE_HELPERS@%$HIPE_HELPERS%g
 s%@HIPE_ENABLED@%$HIPE_ENABLED%g
@@ -7246,6 +7373,7 @@ s%@DED_CFLAGS@%$DED_CFLAGS%g
 s%@DED_LD@%$DED_LD%g
 s%@DED_LDFLAGS@%$DED_LDFLAGS%g
 s%@DED_LD_FLAG_RUNTIME_LIBRARY_PATH@%$DED_LD_FLAG_RUNTIME_LIBRARY_PATH%g
+s%@STATIC_CFLAGS@%$STATIC_CFLAGS%g
 s%@EMU_CC@%$EMU_CC%g
 s%@SSL_APP@%$SSL_APP%g
 s%@CRYPTO_APP@%$CRYPTO_APP%g
