Fixes a configure script regression for mac os x 10.4 users building with HIPE. Patches the configure script to properly detect reliable floating point exceptions under os x 10.4.

diff --git a/erts/configure b/erts/configure
--- a/erts/configure
+++ b/erts/configure
@@ -19166,6 +19166,97 @@ echo "${ECHO_T}not working" >&6
 	;;
 esac
 
+case $ARCH-$OPSYS in
+	amd64-darwin*|x86-darwin*)
+		echo "$as_me:$LINENO: checking For modern (leopard) style mcontext_t" >&5
+echo $ECHO_N "checking For modern (leopard) style mcontext_t... $ECHO_C" >&6
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+				#include <stdlib.h>
+				#include <sys/types.h>
+				#include <unistd.h>
+				#include <mach/mach.h>
+				#include <pthread.h>
+				#include <machine/signal.h>
+				#include <ucontext.h>
+
+int
+main ()
+{
+
+				#if defined(__APPLE__) && defined(__MACH__) && !defined(__DARWIN__)
+				#define __DARWIN__ 1
+				#endif
+
+				#ifndef __DARWIN__
+				#error inpossible
+				#else
+
+    				mcontext_t mc = NULL;
+    				int x = mc->__fs.__fpu_mxcsr;
+
+				#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  darwin_mcontext_leopard=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+darwin_mcontext_leopard=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+				if test X"$darwin_mcontext_leopard" = X"yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define DARWIN_MODERN_MCONTEXT
+_ACEOF
+
+				   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+				else
+				   echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+				fi
+		;;
+	*)
+		darwin_mcontext_leopard=no
+		;;
+esac
+
+
+
+
 if test X${enable_hipe} != Xno; then
   case "$ARCH-$OPSYS" in
     x86-linux|amd64-linux|ppc-linux|ppc-darwin|arm-linux|amd64-freebsd|x86-freebsd|x86-sol2|amd64-sol2|ultrasparc-linux)
@@ -19519,6 +19610,7 @@ static __inline__ int check_fpe(double f)
 #include <machine/fpu.h>
 #elif defined(__DARWIN__)
 #include <machine/signal.h>
+#include <mach/i386/thread_status.h>
 #elif defined(__OpenBSD__) && defined(__x86_64__)
 #include <sys/types.h>
 #include <machine/fpu.h>
@@ -19566,15 +19658,33 @@ static void fpe_sig_action(int sig, siginfo_t *si, void *puc)
 #endif
 #elif defined(__DARWIN__)
 #if defined(__x86_64__)
+#ifdef DARWIN_MODERN_MCONTEXT
      mcontext_t mc = uc->uc_mcontext;
     struct __darwin_x86_float_state64 *fpstate = &mc->__fs;
     fpstate->__fpu_mxcsr = 0x1F80;
     *(unsigned short *)&fpstate->__fpu_fsw &= ~0xFF;
+#else
+    mcontext_t mc = uc->uc_mcontext;
+#if defined(__LP64__)
+    x86_float_state64_t *fpstate = &mc->fs;
+#else
+    x86_float_state32_t *fpstate = &mc->fs;
+#endif
+    fpstate->fpu_mxcsr = 0x1F80;
+    *(unsigned short *)&fpstate->fpu_fsw &= ~0xFF;
+#endif /* DARWIN_MODERN_MCONTEXT */
 #elif defined(__i386__)
+#ifdef DARWIN_MODERN_MCONTEXT
     mcontext_t mc = uc->uc_mcontext;
     struct __darwin_i386_float_state *fpstate = &mc->__fs;
     fpstate->__fpu_mxcsr = 0x1F80;
     *(unsigned short *)&fpstate->__fpu_fsw &= ~0xFF;
+#else
+    mcontext_t mc = uc->uc_mcontext;
+    x86_float_state32_t *fpstate = &mc->fs;
+    fpstate->fpu_mxcsr = 0x1F80;
+    *(unsigned short *)&fpstate->fpu_fsw &= ~0xFF;
+#endif /* DARWIN_MODERN_MCONTEXT */
 #elif defined(__ppc__)
     mcontext_t mc = uc->uc_mcontext;
     mc->ss.srr0 += 4;
@@ -19713,96 +19823,6 @@ echo "${ECHO_T}reliable" >&6
         FPE=reliable
     fi
 fi
-
-case $ARCH-$OPSYS in
-	amd64-darwin*|x86-darwin*)
-		echo "$as_me:$LINENO: checking For modern (leopard) style mcontext_t" >&5
-echo $ECHO_N "checking For modern (leopard) style mcontext_t... $ECHO_C" >&6
-		cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-				#include <stdlib.h>
-				#include <sys/types.h>
-				#include <unistd.h>
-				#include <mach/mach.h>
-				#include <pthread.h>
-				#include <machine/signal.h>
-				#include <ucontext.h>
-
-int
-main ()
-{
-
-				#if defined(__APPLE__) && defined(__MACH__) && !defined(__DARWIN__)
-				#define __DARWIN__ 1
-				#endif
-
-				#ifndef __DARWIN__
-				#error inpossible
-				#else
-
-    				mcontext_t mc = NULL;
-    				int x = mc->__fs.__fpu_mxcsr;
-
-				#endif
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  darwin_mcontext_leopard=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-darwin_mcontext_leopard=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-				if test X"$darwin_mcontext_leopard" = X"yes"; then
-
-cat >>confdefs.h <<\_ACEOF
-#define DARWIN_MODERN_MCONTEXT
-_ACEOF
-
-				   echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-				else
-				   echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-				fi
-		;;
-	*)
-		darwin_mcontext_leopard=no
-		;;
-esac
-
-
 
 
 
