importing R13B01

diff --git a/erts/configure b/erts/configure
--- a/erts/configure
+++ b/erts/configure
@@ -1337,7 +1337,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-if test "x$no_recursion" != "xyes"; then
+if test "x$no_recursion" != "xyes" -a "x$OVERRIDE_CONFIG_CACHE" = "x"; then
     # We do not want to use a common cache!
     cache_file=/dev/null
 fi
@@ -5460,6 +5460,16 @@ esac
 case $host_os in
 	darwin*)
 								INSTALL_DATA="$INSTALL_DATA -p";;
+	*)
+		;;
+esac
+
+
+case $build in
+	*tile*)
+		INSTALL_PROGRAM="$INSTALL_PROGRAM -m755"
+		INSTALL_SCRIPT="$INSTALL_SCRIPT -m755"
+		;;
 	*)
 		;;
 esac
@@ -15511,6 +15521,71 @@ fi
 
 
 if test "x$ac_compiler_gnu" = "xyes"; then
+echo "$as_me:$LINENO: checking if we should add -fno-tree-copyrename to CFLAGS for computed gotos to work properly" >&5
+echo $ECHO_N "checking if we should add -fno-tree-copyrename to CFLAGS for computed gotos to work properly... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+		#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 3)
+			;
+			#else
+			#error old and ok
+			#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  no_tree_copyrename=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+no_tree_copyrename=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+if test "x$no_tree_copyrename" = "xyes"; then
+	CFLAGS="$CFLAGS -fno-tree-copyrename"
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 echo "$as_me:$LINENO: checking for broken gcc-4.3.0 compiler" >&5
 echo $ECHO_N "checking for broken gcc-4.3.0 compiler... $ECHO_C" >&6
 if test "$cross_compiling" = yes; then
diff --git a/lib/megaco/configure b/lib/megaco/configure
--- a/lib/megaco/configure
+++ b/lib/megaco/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="vsn.mk"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LEX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LEXLIB LEX_OUTPUT_ROOT ENABLE_MEGACO_FLEX_SCANNER ENABLE_MEGACO_FLEX_SCANNER_LINENO DED_CFLAGS DED_LD DED_LDFLAGS PERL ERLANG_OSTYPE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LEX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LEXLIB LEX_OUTPUT_ROOT ENABLE_MEGACO_FLEX_SCANNER ENABLE_REENTRANT_MEGACO_FLEX_SCANNER ENABLE_MEGACO_FLEX_SCANNER_LINENO DED_CFLAGS DED_LD DED_LDFLAGS PERL ERLANG_OSTYPE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -803,6 +803,9 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-megaco-reentrant-flex-scanner  enable reentrans megaco flex scanner
+  --disable-megaco-reentrant-flex-scanner  disable reentrans megaco flex scanner
+  --enable-megaco-flex-scanner-lineno  enable megaco flex scanner lineno
   --disable-megaco-flex-scanner-lineno  disable megaco flex scanner lineno
 
 Some influential environment variables:
@@ -1159,6 +1162,22 @@ echo "$as_me: loading site script $ac_site_file" >&6;}
   fi
 done
 
+if test -r "$cache_file"; then
+  # Some versions of bash will fail to source /dev/null (special
+  # files actually), so we avoid doing that.
+  if test -f "$cache_file"; then
+    { echo "$as_me:$LINENO: loading cache $cache_file" >&5
+echo "$as_me: loading cache $cache_file" >&6;}
+    case $cache_file in
+      [\\/]* | ?:[\\/]* ) . $cache_file;;
+      *)                      . ./$cache_file;;
+    esac
+  fi
+else
+  { echo "$as_me:$LINENO: creating cache $cache_file" >&5
+echo "$as_me: creating cache $cache_file" >&6;}
+  >$cache_file
+fi
 
 # Check that the precious variables saved in the cache have kept the same
 # value.
@@ -1351,6 +1370,21 @@ else
 fi
 
 
+
+
+
+
+# Check whether --enable-megaco_reentrant_flex_scanner or --disable-megaco_reentrant_flex_scanner was given.
+if test "${enable_megaco_reentrant_flex_scanner+set}" = set; then
+  enableval="$enable_megaco_reentrant_flex_scanner"
+  if test x${enable_megaco_reentrant_flex_scanner} = xno ; then
+    ENABLE_REENTRANT_MEGACO_FLEX_SCANNER=false
+  else
+    ENABLE_REENTRANT_MEGACO_FLEX_SCANNER=true
+  fi
+else
+  ENABLE_REENTRANT_MEGACO_FLEX_SCANNER=true
+fi;
 
 
 
@@ -2563,7 +2597,61 @@ if test "$LEX" != flex; then
   ENABLE_MEGACO_FLEX_SCANNER=false
 else
   ENABLE_MEGACO_FLEX_SCANNER=true
+      if ${ENABLE_REENTRANT_MEGACO_FLEX_SCANNER} = true ; then
+    flex_compile='$LEX -R -Pconftest -oconftest.c conftest.flex 1>&5'
+cat > conftest.flex <<EOF
+/*
+ * This (reentrant) example code comes from the flex manual
+ */
+
+%option reentrant stack noyywrap
+%x COMMENT
+
+%%
+
+"//"                 yy_push_state( COMMENT, yyscanner);
+.|\n
+
+<COMMENT>\n          yy_pop_state( yyscanner );
+<COMMENT>[^\n]+      fprintf( yyout, "%s\n", yytext);
+
+%%
+
+int main ( int argc, char * argv[] )
+{
+  yyscan_t scanner;
+
+  yylex_init ( &scanner );
+  yylex ( scanner );
+  yylex_destroy ( scanner );
+  return 0;
+}
+EOF
+echo "$as_me:$LINENO: checking for reentrant capable flex" >&5
+echo $ECHO_N "checking for reentrant capable flex... $ECHO_C" >&6
+if { (eval echo "$as_me:$LINENO: \"$flex_compile\"") >&5
+  (eval $flex_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest.c; then
+
+   ENABLE_REENTRANT_MEGACO_FLEX_SCANNER=true
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+   echo "configure: failed program was:" 1>&5
+   cat conftest.flex 1>&5
+   echo "configure: PATH was $PATH" 1>&5
+
+  ENABLE_REENTRANT_MEGACO_FLEX_SCANNER=false
+   echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
+
+  fi
+fi
+
+
 
 
 
@@ -3320,6 +3408,126 @@ else
 fi
 
 
+echo "$as_me:$LINENO: checking for struct ErlDrvEntry.stop_select" >&5
+echo $ECHO_N "checking for struct ErlDrvEntry.stop_select... $ECHO_C" >&6
+if test "${ac_cv_member_struct_ErlDrvEntry_stop_select+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                  #include "erl_driver.h"
+
+
+int
+main ()
+{
+static struct ErlDrvEntry ac_aggr;
+if (ac_aggr.stop_select)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_struct_ErlDrvEntry_stop_select=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+                  #include "erl_driver.h"
+
+
+int
+main ()
+{
+static struct ErlDrvEntry ac_aggr;
+if (sizeof ac_aggr.stop_select)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_struct_ErlDrvEntry_stop_select=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_member_struct_ErlDrvEntry_stop_select=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_member_struct_ErlDrvEntry_stop_select" >&5
+echo "${ECHO_T}$ac_cv_member_struct_ErlDrvEntry_stop_select" >&6
+if test $ac_cv_member_struct_ErlDrvEntry_stop_select = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_STRUCT_ERLDRVENTRY_STOP_SELECT 1
+_ACEOF
+
+
+                  CFLAGS="$CFLAGS -DMEGACO_DRV_ENTRY_HAS_STOP_SELECT"
+
+fi
+
+
+
 CFLAGS="$CFLAGS -I${ERL_TOP}/erts/$host $OTP_EXTRA_FLAGS"
 
 if test "X$host" = "Xwin32"; then
@@ -3474,7 +3682,60 @@ fi
 
 
           ac_config_files="$ac_config_files src/flex/$host/Makefile:src/flex/Makefile.in"
+cat >confcache <<\_ACEOF
+# This file is a shell script that caches the results of configure
+# tests run on this system so they can be shared between configure
+# scripts and configure runs, see configure's option --config-cache.
+# It is not useful on other systems.  If it contains results you don't
+# want to keep, you may remove or edit it.
+#
+# config.status only pays attention to the cache file if you give it
+# the --recheck option to rerun configure.
+#
+# `ac_cv_env_foo' variables (set or unset) will be overridden when
+# loading this file, other *unset* `ac_cv_foo' will be assigned the
+# following values.
 
+_ACEOF
+
+# The following way of writing the cache mishandles newlines in values,
+# but we know of no workaround that is simple, portable, and efficient.
+# So, don't put newlines in cache variables' values.
+# Ultrix sh set writes to stderr and can't be redirected directly,
+# and sets the high bit in the cache file unless we assign to the vars.
+{
+  (set) 2>&1 |
+    case `(ac_space=' '; set | grep ac_space) 2>&1` in
+    *ac_space=\ *)
+      # `set' does not quote correctly, so add quotes (double-quote
+      # substitution turns \\\\ into \\, and sed turns \\ into \).
+      sed -n \
+	"s/'/'\\\\''/g;
+	  s/^\\([_$as_cr_alnum]*_cv_[_$as_cr_alnum]*\\)=\\(.*\\)/\\1='\\2'/p"
+      ;;
+    *)
+      # `set' quotes correctly as required by POSIX, so do not add quotes.
+      sed -n \
+	"s/^\\([_$as_cr_alnum]*_cv_[_$as_cr_alnum]*\\)=\\(.*\\)/\\1=\\2/p"
+      ;;
+    esac;
+} |
+  sed '
+     t clear
+     : clear
+     s/^\([^=]*\)=\(.*[{}].*\)$/test "${\1+set}" = set || &/
+     t end
+     /^ac_cv_env/!s/^\([^=]*\)=\(.*\)$/\1=${\1=\2}/
+     : end' >>confcache
+if diff $cache_file confcache >/dev/null 2>&1; then :; else
+  if test -w $cache_file; then
+    test "x$cache_file" != "x/dev/null" && echo "updating cache $cache_file"
+    cat confcache >$cache_file
+  else
+    echo "not updating unwritable cache $cache_file"
+  fi
+fi
+rm -f confcache
 
 test "x$prefix" = xNONE && prefix=$ac_default_prefix
 # Let make expand exec_prefix.
@@ -4074,6 +4335,7 @@ s,@OBJEXT@,$OBJEXT,;t t
 s,@LEXLIB@,$LEXLIB,;t t
 s,@LEX_OUTPUT_ROOT@,$LEX_OUTPUT_ROOT,;t t
 s,@ENABLE_MEGACO_FLEX_SCANNER@,$ENABLE_MEGACO_FLEX_SCANNER,;t t
+s,@ENABLE_REENTRANT_MEGACO_FLEX_SCANNER@,$ENABLE_REENTRANT_MEGACO_FLEX_SCANNER,;t t
 s,@ENABLE_MEGACO_FLEX_SCANNER_LINENO@,$ENABLE_MEGACO_FLEX_SCANNER_LINENO,;t t
 s,@DED_CFLAGS@,$DED_CFLAGS,;t t
 s,@DED_LD@,$DED_LD,;t t
